#!/bin/bash
yum install -y yum-utils
yum install git -y
yum install wget vim -y
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum-config-manager --enable docker-ce-nightly
yum-config-manager --enable docker-ce-test
yum-config-manager --disable docker-ce-nightly
yum install docker-ce docker-ce-cli containerd.io
systemctl start docker
systemctl enable docker
yum install git -y
yum install vim -y
yum install wget -y
sed -i 's/^#PermitRootLogin yes$/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/^PasswordAuthentication no$/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl restart sshd
systemctl enable sshd
echo "docker" | passwd --stdin root
hostnamectl set-hostname docker
