#!/bin/bash
sed -i 's/^#PermitRootLogin yes$/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/^PasswordAuthentication no$/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl restart sshd
systemctl enable sshd
echo "NFS" | passwd --stdin root
hostnamectl set-hostname nfsserver
mkdir /data
chmod 757 /data
yum install nfs-utils -y
yum install wget -y
yum install vim -y
sed -i 's/^SELINUX=enforcing$/SELINUX=disabled/' /etc/selinux/config
echo "/data   *(rw,sync)" > /etc/exports
systemctl start nfs-server
systemctl enable nfs-server
exportfs -rv
