#!/bin/bash
yum install httpd -y
systemctl start httpd
systemctl enable httpd
yum install git -y
yum install vim -y
yum install wget -y
sed -i 's/^#PermitRootLogin yes$/PermitRootLogin yes/' /etc/ssh/sshd_config
sed -i 's/^PasswordAuthentication no$/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl restart sshd
systemctl enable sshd
echo "webserver" | passwd --stdin root
hostnamectl set-hostname webserver
